const vietnameseError: Record<string, string> = {
  INVALID_CREDENTIALS: "Sai tên đăng nhập hoặc mật khẩu.",
  USERNAME_TAKEN: "Tên đăng nhập đã tồn tại.",
  ACCOUNT_BANNED: "Tài khoản đã bị khóa, không thể thao tác.",
  TARGET_FROZEN: "Mục tiêu đang bị đóng băng.",
  RATE_LIMITED: "Thao tác quá nhanh, xin chờ một lát.",
  UNAUTHORIZED: "Chưa đăng nhập hoặc phiên đã hết hạn.",
  SESSION_EXPIRED: "Phiên đăng nhập đã hết hạn.",
  ORIGIN_NOT_ALLOWED: "Yêu cầu bị từ chối vì nguồn gốc không hợp lệ.",
  INVALID_DEV_ACCOUNT: "Tên hoặc phe không hợp lệ.",
  INVALID_DISPLAY_NAME: "Tên hiển thị không hợp lệ (2–32 ký tự).",
  INVALID_REQUEST: "Yêu cầu không hợp lệ.",
  NOT_FOUND: "Không tìm thấy.",
  TARGET_NOT_FOUND: "Không tìm thấy quân mục tiêu.",
  ARMY_NOT_FOUND: "Không tìm thấy quân đội.",
  CITY_NOT_FOUND: "Không tìm thấy thành phố.",
  CITY_ACCESS_DENIED: "Bạn không thể điều khiển thành phố này.",
  CITY_PLOT_OUT_OF_BOUNDS: "Ô này chưa nằm trong phần nội thành đã mở rộng.",
  CITY_PLOT_OCCUPIED: "Ô này đã có công trình.",
  CITY_FULL: "Nội thành đã hết ô trống; hãy nâng Tòa thị chính.",
  BUILDING_ALREADY_PLACED: "Công trình này đã có vị trí trong thành.",
  BUILDING_ALREADY_QUEUED: "Công trình này đang ở trong hàng đợi xây.",
  ARMY_ACCESS_DENIED: "Bạn không thể điều khiển quân đội này.",
  NO_ATTACK_ORDER: "Quân đội này không có lệnh tấn công.",
  NOT_ENOUGH_RESOURCES: "Không đủ tài nguyên.",
  INSUFFICIENT_RESOURCES: "Không đủ tài nguyên.",
  NODE_NOT_FOUND: "Không tìm thấy mỏ tài nguyên.",
  ROUTE_NOT_FOUND: "Không tìm thấy tuyến đường.",
  CARAVAN_NOT_FOUND: "Không tìm thấy caravan.",
  NO_DEPOT: "Cần xây trạm tiếp tế (road_depot) trước.",
  COOLDOWN_ACTIVE: "Còn trong thời gian chờ.",
  SERVER_VERIFIED_STEP: "Bước này do hệ thống tự kiểm tra.",
  ALLIANCE_FULL: "Liên minh đã đầy (10 thành viên).",
  NOT_IN_ALLIANCE: "Bạn không thuộc liên minh này.",
  ALLIANCE_NOT_FOUND: "Không tìm thấy liên minh.",
  TREATY_NOT_FOUND: "Không tìm thấy hiệp ước.",
  KINGDOM_FULL: "Vương quốc đã đầy, không thể tạo thêm thành phố.",
  INVALID_TARGET: "Mục tiêu không hợp lệ.",
  ARMY_DESTROYED: "Quân đội đã bị tiêu diệt.",
  CITY_LAYOUT_STALE: "Quy hoạch thành đã bị thay đổi ở phiên khác. Vui lòng thử lại.",
  CITY_LAYOUT_INVALID_SET: "Danh sách công trình quy hoạch không khớp với thành phố.",
  CITY_BUILDING_LOCKED: "Công trình đang nâng cấp không thể di chuyển.",
  INVALID_BUILDING_ROTATION: "Góc xoay công trình không hợp lệ.",
  SEASON_NOT_ACTIVE: "Mùa giải hiện tại chưa bắt đầu hoặc đã kết thúc.",
};

Object.assign(vietnameseError, {
  UNKNOWN_REWARD: "Khong tim thay phan thuong.",
  REWARD_ALREADY_CLAIMED: "Phan thuong nay da duoc nhan.",
  REWARD_NOT_AVAILABLE: "Phan thuong chua du dieu kien.",
  UNKNOWN_COSMETIC: "Khong tim thay cosmetic.",
  COSMETIC_ALREADY_OWNED: "Ban da so huu mon nay.",
  INSUFFICIENT_BADGES: "Khong du Huy hieu.",
  COSMETIC_NOT_OWNED: "Ban chua so huu cosmetic nay.",
  HUB_FAILED: "Khong tai duoc hub nguoi choi.",
});

export function errorMessage(code: string): string {
  return vietnameseError[code] ?? code;
}
