const vietnameseError: Record<string, string> = {
  INVALID_CREDENTIALS: "Sai tên đăng nhập hoặc mật khẩu.",
  USERNAME_TAKEN: "Tên đăng nhập đã tồn tại.",
  ACCOUNT_BANNED: "Tài khoản đã bị khóa, không thể thao tác.",
  TARGET_FROZEN: "Mục tiêu đang bị đóng băng.",
  RATE_LIMITED: "Thao tác quá nhanh, xin chờ một lát.",
  UNAUTHORIZED: "Chưa đăng nhập hoặc phiên đã hết hạn.",
  SESSION_EXPIRED: "Phiên đăng nhập đã hết hạn.",
  ORIGIN_NOT_ALLOWED: "Yêu cầu bị từ chối vì nguồn gốc không hợp lệ.",
  INVALID_DEV_ACCOUNT: "Tên hoặc phe không hợp lệ.",
  INVALID_DISPLAY_NAME: "Tên hiển thị không hợp lệ (2–32 ký tự).",
  INVALID_REQUEST: "Yêu cầu không hợp lệ.",
  NOT_FOUND: "Không tìm thấy.",
  TARGET_NOT_FOUND: "Không tìm thấy quân mục tiêu.",
  ARMY_NOT_FOUND: "Không tìm thấy quân đội.",
  CITY_NOT_FOUND: "Không tìm thấy thành phố.",
  CITY_ACCESS_DENIED: "Bạn không thể điều khiển thành phố này.",
  ARMY_ACCESS_DENIED: "Bạn không thể điều khiển quân đội này.",
  NO_ATTACK_ORDER: "Quân đội này không có lệnh tấn công.",
  NOT_ENOUGH_RESOURCES: "Không đủ tài nguyên.",
  INSUFFICIENT_RESOURCES: "Không đủ tài nguyên.",
  NODE_NOT_FOUND: "Không tìm thấy mỏ tài nguyên.",
  ROUTE_NOT_FOUND: "Không tìm thấy tuyến đường.",
  CARAVAN_NOT_FOUND: "Không tìm thấy caravan.",
  NO_DEPOT: "Cần xây trạm tiếp tế (road_depot) trước.",
  COOLDOWN_ACTIVE: "Còn trong thời gian chờ.",
  SERVER_VERIFIED_STEP: "Bước này do hệ thống tự kiểm tra.",
  ALLIANCE_FULL: "Liên minh đã đầy (10 thành viên).",
  NOT_IN_ALLIANCE: "Bạn không thuộc liên minh này.",
  ALLIANCE_NOT_FOUND: "Không tìm thấy liên minh.",
  TREATY_NOT_FOUND: "Không tìm thấy hiệp ước.",
  KINGDOM_FULL: "Vương quốc đã đầy, không thể tạo thêm thành phố.",
  INVALID_TARGET: "Mục tiêu không hợp lệ.",
  ARMY_DESTROYED: "Quân đội đã bị tiêu diệt.",
};

export function errorMessage(code: string): string {
  return vietnameseError[code] ?? code;
}