import Fastify, { type FastifyInstance } from "fastify";
import cors from "@fastify/cors";
import { Counter, Histogram, Registry } from "prom-client";
import { buildCommandSchema, caravanCommandSchema, factions, factionIds, harvestCommandSchema, routeCommandSchema, escortCommandSchema, ambushCommandSchema, attackCommandSchema, moveArmyCommandSchema, recruitCommandSchema, setFormationCommandSchema, mergeArmyCommandSchema, type ServerMessage, type WorldSnapshot } from "@kingdoms/shared";
import { WebSocketServer, WebSocket } from "ws";
import { randomUUID } from "node:crypto";
import { config } from "./config.js";
import { RateLimiter } from "./rate-limit.js";
import { GameStore } from "./store.js";

export function createServer(): { app: FastifyInstance; store: GameStore; start: () => Promise<void> } {
  const app = Fastify({ logger: true }); const store = new GameStore(); const limiter = new RateLimiter(); const tokens = new Map<string, string>(); const clients = new Set<WebSocket>(); const registry = new Registry();
  const commandCounter = new Counter({ name: "kingdom_commands_total", help: "Accepted and rejected game commands", labelNames: ["command", "result"], registers: [registry] });
  const commandDuration = new Histogram({ name: "kingdom_command_duration_ms", help: "Game command duration in milliseconds", labelNames: ["command"], registers: [registry] }); let saveTimer: NodeJS.Timeout | undefined; let tickTimer: NodeJS.Timeout | undefined;
  const getSnapshot = (): WorldSnapshot => ({ kingdom: store.snapshot.kingdom, season: { id: store.snapshot.season.id, status: store.snapshot.season.status, endsAt: store.snapshot.season.endsAt }, cities: store.snapshot.cities.map(city => ({ ...city, playerName: store.findPlayer(city.playerId)?.displayName ?? "Unknown" })), caravans: store.logistics.caravans(), armies: store.snapshot.armies, heroes: store.snapshot.heroes, scores: store.snapshot.scores, factionCatalog: factions, logistics: store.logistics.snapshot(), battleReports: store.snapshot.battleReports, terrainMap: store.snapshot.terrainMap });
  const send = (socket: WebSocket, message: ServerMessage) => { if (socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify(message)); }; const broadcast = () => { const message: ServerMessage = { type: "SNAPSHOT", payload: getSnapshot() }; for (const client of clients) send(client, message); };
  const playerFromRequest = (request: { headers: { authorization?: string } }) => { const token = request.headers.authorization?.replace(/^Bearer\s+/i, ""); return token ? tokens.get(token) : undefined; }; const rateLimited = async (key: string, limit: number, windowMs: number) => !(await limiter.consume(key, limit, windowMs));
  const command = async (name: string, request: any, reply: any, action: (playerId: string) => unknown, rlLimit = 20) => { const started = performance.now(); const playerId = playerFromRequest(request); if (!playerId) return reply.code(401).send({ code: "UNAUTHORIZED" }); if (await rateLimited(`write:${playerId}`, rlLimit, 60_000)) return reply.code(429).send({ code: "RATE_LIMITED" }); const body = request.body as { commandId?: string }; if (body.commandId && store.ledger.hasCommand(body.commandId)) return { accepted: true, result: "already_processed", snapshot: getSnapshot() }; try { const result = action(playerId); store.ledger.append({ eventType: `${name}.accepted`, aggregateType: name, aggregateId: playerId, commandId: body.commandId, actorPlayerId: playerId, payload: result }); commandCounter.inc({ command: name, result: "accepted" }); commandDuration.observe({ command: name }, performance.now() - started); await store.save(); broadcast(); return { accepted: true, result, snapshot: getSnapshot() }; } catch (error) { commandCounter.inc({ command: name, result: "rejected" }); commandDuration.observe({ command: name }, performance.now() - started); const message = error instanceof Error ? error.message : "INVALID_COMMAND"; return reply.code(message.includes("ACCESS") ? 403 : 400).send({ code: message }); } };
  app.register(cors, { origin: true }); app.get("/health", async () => ({ ok: true, service: "kingdoms-server" })); app.get("/metrics", async (_request, reply) => reply.type(registry.contentType).send(await registry.metrics()));
  app.post<{ Body: { displayName?: string; factionId?: string } }>("/api/auth/dev", async (request, reply) => { if (await rateLimited(`login:${request.ip}`, 10, 60_000)) return reply.code(429).send({ code: "RATE_LIMITED" }); const displayName = request.body?.displayName?.trim(); const factionId = request.body?.factionId; if (!displayName || !factionId || !factionIds.includes(factionId as typeof factionIds[number])) return reply.code(400).send({ code: "INVALID_DEV_ACCOUNT" }); const player = store.addDevPlayer(displayName, factionId as typeof factionIds[number]); store.recalculateScores(); const token = randomUUID(); tokens.set(token, player.id); store.ledger.append({ eventType: "auth.accepted", aggregateType: "player", aggregateId: player.id, actorPlayerId: player.id, payload: { displayName: player.displayName, factionId: player.factionId } }); await store.save(); return { token, player, snapshot: getSnapshot() }; });
  app.get("/api/bootstrap", async (request, reply) => { const playerId = playerFromRequest(request); if (!playerId) return reply.code(401).send({ code: "UNAUTHORIZED" }); return { player: store.findPlayer(playerId), snapshot: getSnapshot() }; });
  app.post<{ Body: unknown }>("/api/commands/build", async (request, reply) => command("build", request, reply, playerId => { const c = buildCommandSchema.parse(request.body); return store.startBuild(playerId, c.commandId, c.cityId, c.buildingId, c.queueType); }));
  app.post<{ Body: unknown }>("/api/commands/harvest", async (request, reply) => command("harvest", request, reply, playerId => { const c = harvestCommandSchema.parse(request.body); return store.logistics.harvest(c.commandId, c.nodeId, c.cityId, playerId, c.amount, store.snapshot); }));
  app.post<{ Body: unknown }>("/api/commands/routes", async (request, reply) => command("route", request, reply, playerId => { const c = routeCommandSchema.parse(request.body); return store.logistics.createRoute(c.commandId, c.sourceCityId, c.destinationCityId, playerId, store.snapshot); }));
  app.post<{ Body: unknown }>("/api/commands/caravans", async (request, reply) => command("caravan", request, reply, playerId => { const c = caravanCommandSchema.parse(request.body); return store.logistics.startCaravan(c.commandId, c.routeId, { food: 0, ...c.cargo }, playerId, store.snapshot); }));
  app.post<{ Body: unknown }>("/api/commands/escort", async (request, reply) => command("escort", request, reply, playerId => { const c = escortCommandSchema.parse(request.body); return store.logistics.escort(c.commandId, c.caravanId, c.armyId, playerId, store.snapshot); }));
  app.post<{ Body: unknown }>("/api/commands/ambush", async (request, reply) => command("ambush", request, reply, playerId => { const c = ambushCommandSchema.parse(request.body); return store.logistics.ambush(c.commandId, c.caravanId, playerId, store.snapshot); }));
  
  // Phase 3 Combat commands (lower rate limit 10/min)
  app.post<{ Body: unknown }>("/api/commands/recruit", async (request, reply) => command("recruit", request, reply, playerId => { const c = recruitCommandSchema.parse(request.body); return store.combat.recruit(c.commandId, c.cityId, c.unitType, c.amount, playerId, store.snapshot); }, 10));
  app.post<{ Body: unknown }>("/api/commands/move-army", async (request, reply) => command("move_army", request, reply, playerId => { const c = moveArmyCommandSchema.parse(request.body); return store.combat.moveArmy(c.commandId, c.armyId, c.targetX, c.targetY, playerId, store.snapshot); }, 10));
  app.post<{ Body: unknown }>("/api/commands/attack", async (request, reply) => command("attack", request, reply, playerId => { const c = attackCommandSchema.parse(request.body); const report = store.combat.attack(c.commandId, c.armyId, c.targetArmyId, playerId, store.snapshot, store.diplomacy); for (const client of clients) send(client, { type: "BATTLE_REPORT", payload: report }); return report; }, 10));
  app.post<{ Body: unknown }>("/api/commands/formation", async (request, reply) => command("set_formation", request, reply, playerId => { const c = setFormationCommandSchema.parse(request.body); return store.combat.setFormation(c.commandId, c.armyId, c.formation, playerId, store.snapshot); }, 10));
  app.post<{ Body: unknown }>("/api/commands/merge-army", async (request, reply) => command("merge_army", request, reply, playerId => { const c = mergeArmyCommandSchema.parse(request.body); return store.combat.mergeArmies(c.commandId, c.sourceArmyId, c.targetArmyId, playerId, store.snapshot); }, 10));

  const websocketServer = new WebSocketServer({ noServer: true }); app.server.on("upgrade", (request, socket, head) => { const url = new URL(request.url ?? "/", "http://localhost"); if (url.pathname !== "/ws") return; const playerId = tokens.get(url.searchParams.get("token") ?? ""); if (!playerId) return socket.destroy(); websocketServer.handleUpgrade(request, socket, head, client => websocketServer.emit("connection", client, request, playerId)); });
  websocketServer.on("connection", (socket: WebSocket, _request: unknown, playerId: string) => { clients.add(socket); send(socket, { type: "SNAPSHOT", payload: getSnapshot() }); socket.on("close", () => clients.delete(socket)); });
  const start = async () => { await store.load(); store.recalculateScores(); await app.listen({ host: config.host, port: config.port }); tickTimer = setInterval(() => { const changed = store.tick(); const finalized = store.finalizeIfDue(); if (changed || finalized) { void store.save(); broadcast(); } }, config.tickMs); saveTimer = setInterval(() => void store.save(), 10_000); };
  app.addHook("onClose", async () => { if (tickTimer) clearInterval(tickTimer); if (saveTimer) clearInterval(saveTimer); await store.save(); }); return { app, store, start };
}



